#{
  import "requirements.typ": wut-thesis, glossarium, drafting
  import wut-thesis: wut-thesis, acknowledgements, figure-outline, table-outline, appendix
  import "utils.typ": flex-caption-styles, todo, glossary-outline
  import "glossary.typ": glossary
  import glossarium: make-glossary, register-glossary
  import drafting: note-outline, set-margin-note-defaults

  show: make-glossary
  register-glossary(glossary)
  show: flex-caption-styles


  /** Drafting

    The "draft" variable is used to change the coloring of links, show TODOs (both in
    the thesis and TODO outline), as well as DRAFT in the header and the title. This
    should be true until the final version is handed-in.

    The "in-print" variable is used to generate a PDF file for physical printing (it adds
    bigger margins on the binding part of the page and changes the numbering placement).
    It should be set to `false` unless you want to create a version of the PDF file for
    physical print, in which case set it to `true`. To prepare a PDF file for the
    final hand-in (that is to upload it to APD/onedrive) please set this variable to
    `false`. variable to false.

  **/
  let draft = true
  let in-print = false
  set-margin-note-defaults(hidden: not draft)

  /// Set the languages of your studies and thesis.
  let lang = (
    /// Language in which you studied, influences the language of the titlepage.
    studies: "pl",
    /// Language in which your thesis is written, influences the rest of the text (i.e.
    /// abstracts order, captions/references supplements, hyphenation etc).
    thesis: "pl"
  )

  show: wut-thesis.with(
    draft: draft,
    in-print: in-print,
    lang: lang,
    // Dane z docs/MasterThesisShorten.pdf.
    titlepage-info: (
      thesis-type: "master", // praca magisterska (inne wartości: "bachelor", "engineer")
      program: "Informatyka Stosowana", // pol. kierunek
      specialisation: "Informatyka Stosowana", // pol. specjalność
      institute: "Politechnika Warszawska", // brak w dokumencie — uzupełnij (Wydz. Elektryczny)
      supervisor: "dr inż. Jarosław Wilk",
      // Opcjonalny konsultant — na stronie tytułowej jako `konsultacje`.
      advisor: none, // lub "tytuł Imię Nazwisko"
      // Kod wydziału. Dozwolone wartości (z src/template.typ pakietu wut-thesis):
      //   kneis, wains, warch, wbmip, wch, we, weiti, wf, wgik, wichip, wil,
      //   wim, wis, wmeil, wmini, wmchtr, wmt, wsimr, wt, wz
      // "we" = Wydział Elektryczny (wywnioskowane z kierunku "Informatyka Stosowana").
      faculty: "we", // POTWIERDŹ: czy na pewno Wydział Elektryczny?
      index-number: "317008",
      date: datetime.today(),
    ),
    // Jeśli nie chcesz generować strony tytułowej (np. używasz tej z APD),
    // zakomentuj powyższy blok `titlepage-info` i odkomentuj poniższą linię:
    // titlepage-info: none,
    author: "Illia Mishkin",
    // Pola poniżej wypełnij DWUJĘZYCZNIE (en + pl) niezależnie od języka pracy.
    title: (
      en: "Design and implementation of a secure gateway for data anonymization in communication with LLM models",
      pl: "Projekt i implementacja bezpiecznego gatewaya do anonimizacji danych w komunikacji z modelami LLM",
    ),
    abstract: (
      en: [
        // max 1 page
        The main objective of this thesis was to design and implement a gateway proxy system that
        pseudonymizes personal data in requests sent to external language models and then restores it in the
        responses generated by the model. The work focuses on the problem of personal data protection in
        the context of using commercial LLMs in corporate environments, where sensitive data is increasingly
        processed without full control over its further use. An important part of the thesis is also the analysis
        of the impact of pseudonymization on the usefulness of language model responses.

        The thesis consists of seven chapters. The introduction presents the context of LLM usage and the
        resulting privacy risks. The second chapter discusses threat mechanisms, including the phenomenon
        of data memorization by models as well as risks related to API interfaces and legal regulations such
        as GDPR and the EU AI Act.

        The following chapters focus on the theoretical foundations of data protection in AI systems,
        including the distinction between anonymization and pseudonymization, data masking techniques, and
        challenges in named entity recognition in the Polish language. Next, the design and implementation
        of the gateway system are presented, covering its architecture, pseudonymization mechanisms, API
        layer, and integration with language models.

        The final chapter is devoted to system evaluation, including an assessment of pseudonymization
        effectiveness and its impact on the quality of LLM responses in tasks involving the analysis of Polish
        civil law contracts. The thesis concludes with a synthesis of results and an answer to the research
        question posed.
      ],
      pl: [
        // max 1 strona
        Głównym celem pracy było zaprojektowanie i implementacja systemu gateway proxy, który
        pseudonimizuje dane osobowe w zapytaniach wysyłanych do zewnętrznych modeli językowych, a następnie
        przywraca je w odpowiedziach generowanych przez model. Praca koncentruje się na problemie
        ochrony danych osobowych w kontekście wykorzystania komercyjnych modeli LLM w środowiskach
        korporacyjnych, gdzie coraz częściej przetwarzane są dane wrażliwe bez pełnej kontroli nad ich
        dalszym wykorzystaniem. Istotnym elementem pracy jest również analiza wpływu pseudonimizacji
        na użyteczność odpowiedzi modeli językowych.

        Praca składa się z siedmiu rozdziałów. Wprowadzenie przedstawia kontekst wykorzystania modeli
        LLM oraz wynikające z tego ryzyka dla prywatności danych. W drugim rozdziale omówiono
        mechanizmy zagrożeń, w tym zjawisko zapamiętywania danych przez modele oraz ryzyka związane
        z interfejsami API i regulacjami prawnymi RODO oraz EU AI Act.

        Kolejne rozdziały koncentrują się na podstawach teoretycznych ochrony danych w systemach AI,
        w tym różnicy między anonimizacją a pseudonimizacją, technikach maskowania danych oraz
        wyzwaniach rozpoznawania encji w języku polskim. Następnie przedstawiono projekt oraz implementację
        systemu gateway, obejmujące architekturę, mechanizmy pseudonimizacji, warstwę API oraz integrację
        z modelami językowymi.

        Ostatni rozdział poświęcony jest ewaluacji systemu, obejmującej ocenę skuteczności
        pseudonimizacji oraz wpływu tego procesu na jakość odpowiedzi modeli LLM w zadaniach analizy polskich
        umów cywilnoprawnych. Praca kończy się syntetycznym podsumowaniem wyników oraz odpowiedzią
        na postawione pytanie badawcze.
      ],
    ),
    keywords: (
      en: ("gateway", "data anonymization", "pseudonymization", "LLM", "NER", "personal data protection"),
      pl: ("gateway", "anonimizacja danych", "pseudonimizacja", "LLM", "NER", "ochrona danych osobowych"),
    ),
  )

  // --- Custom Settings ---
  // if you want to override any settings from the template here is the place to do so,
  // e.g.:
  // Use Comic Sans Font
  // set text(font: "Comic Sans MS")
  // Use nicer microtypography
  set par(justification-limits: (
    tracking: (min: -0.01em, max: 0.02em),
  ))


  // --- Rozdziały pracy (struktura z docs/MasterThesisShorten.pdf) ---
  // Ściąga ze składni Typst — referencja, NIE część pracy. Odkomentuj, gdy potrzebna:
  // include "content/Tutorial.typ"
  include "content/01-wstep/01-wstep.typ"
  include "content/02-prywatnosc-danych/02-prywatnosc-danych.typ"
  include "content/03-anonimizacja-pseudonimizacja/03-anonimizacja-pseudonimizacja.typ"
  include "content/04-projekt-gatewaya/04-projekt-gatewaya.typ"
  include "content/05-implementacja/05-implementacja.typ"
  include "content/06-testy-ewaluacja/06-testy-ewaluacja.typ"
  include "content/07-podsumowanie/07-podsumowanie.typ"

  // --- Acknowledgements ---
  // You can put your acknowledgements (pol. podziękowania) here.
  // Below is an example containing acknowledgements for the PLGrid grant.
  // Comment out if not needed.
  acknowledgements[
    We gratefully acknowledge Poland's high-performance Infrastructure PLGrid
    #text(fill: red)[(wybierz właściwy ośrodek z listy: ACK Cyfronet AGH, PCSS, CI TASK,
      WCSS)] for providing computer facilities and support within computational grant no
    #text(fill: red)[(numer grantu)]
    #todo[Numer grantu i typ ośrodka]
  ]

  // --- Bibliography ---
  bibliography("items.bib", style: "ieee")

  // List of Acronyms - comment out, if not needed (no abbreviations were used).
  glossary-outline(glossary)

  // List of figures - comment out, if not needed.
  figure-outline(lang.thesis)

  // List of tables - comment out, if not needed.
  table-outline(lang.thesis)

  // --- Appendices ---
  // Comment out if not needed.
  // appendix(lang.thesis, include "content/Appendix.typ")

  if draft {
    set heading(numbering: none)
    note-outline(title: "TODOs")
  }
}
